Repository SuperDARNCanada/borealis, pull requests merged in 2023-03, with the labels that each got.

#372 Scheduler testing
  scheduler/email_utils.py
  scheduler/local_scd_server.py
  scheduler/remote_server.py
  scheduler/remote_server_options.py
  scheduler/scd_utils.py
  scheduler/schedule_modifier.py
  scripts/install_radar_deps.py
  tests/scheduler/bad_config_file.ini
  tests/scheduler/bad_experiment.swg
  tests/scheduler/complicated_schedule.swg
  tests/scheduler/empty_config_file.ini
  tests/scheduler/good_config_file.ini
  tests/scheduler/good_scd_file.scd
  tests/scheduler/incorrect_args.scd
  tests/scheduler/missing_hours.swg
  tests/scheduler/test_scheduler.py
Labels: testing

#382 Zero interferometer USRP driver bug
  src/data_write.py
  src/usrp_drivers/utils/driveroptions.cpp
Labels: bug, quick review

#384 Changed logging for sending/receiving experiments
  src/experiment_handler.py
  src/radar_control.py
Labels: quick review

#388 Docs build / scheduler config parsing bugfix
  docs/conf.py
  docs/requirements.txt
  docs/source/utils.rst
  scheduler/remote_server_options.py
Labels: bug, quick review

#379 Changed up the correlation calculations to avoid unnecessary multipli…
  src/rx_signal_processing.py
Labels: speed-optimization, quick review

#396 Removed options and log_config dependency from ReadTheDocs
  docs/conf.py
Labels: documentation, quick review

#389 second logging pass
  scheduler/remote_server_options.py
  scheduler/scd_utils.py
  scripts/install_radar_deps.py
  scripts/merge_logs.sh
  scripts/steamed_hams.py
  src/brian.py
  src/data_write.py
  src/experiment_handler.py
  src/radar_status.py
  src/realtime.py
  src/rx_signal_processing.py
  src/usrp_driver.py
  src/utils/log_config.py
  src/utils/options.py
Labels: quick review
