Repository SuperDARNCanada/borealis, pull requests merged in 2024-06, with the labels that each got.

#491 Rich Printer Crashes
  tests/log_printer/json_to_rich_logs.py
Labels: quick review

#492 Bugfix/cfs mask
  src/data_write.py
  src/experiment_prototype/interface_classes/averaging_periods.py
  src/experiment_prototype/interface_classes/sequences.py
  src/radar_control.py
Labels: bug

#493 Cupy mem allocation
  src/experiment_prototype/interface_classes/averaging_periods.py
  src/rx_signal_processing.py
  src/utils/signals.py
Labels: enhancement, quick review
