Repository SuperDARNCanada/borealis, pull requests merged in 2024-10, with the labels that each got.

#506 Lock first pulse in sequence to next millisecond
  src/usrp_drivers/usrp_driver.cpp
Labels: quick review

#508 Fixed not referencing correct cfs data during stable time
  src/radar_control.py
Labels: bug, quick review

#505 Software setup documentation update
  README.md
  docs/source/scheduling.rst
  docs/source/setup_hardware.rst
  docs/source/setup_software.rst
  docs/source/starting_the_radar.rst
  scripts/install_radar_deps.py
Labels: documentation

#509 Cfs/cfs data bugfix
  src/radar_control.py
Labels: bug, quick review

#510 Cfs/cfs data bugfix
  src/radar_control.py
Labels: bug
