Repository SuperDARNCanada/borealis, pull requests merged in 2024-04, with the labels that each got.

#438 Bugfix/bad records
  src/data_write.py
Labels: quick review

#451 Bugfix/filter correction
  docs/requirements.txt
  src/utils/signals.py
Labels: bug

#445 Fixed bug in local_scd_server.py
  scheduler/local_scd_server.py
Labels: bug

#454 Warn if cupy not installed
  src/rx_signal_processing.py
Labels: quick review

#453 Scheduler revamp
  docs/source/scheduling.rst
  scheduler/email_utils.py
  scheduler/local_scd_server.py
  scheduler/quick_test_scdutils.py
  scheduler/remote_server.py
  scheduler/remote_server_options.py
  scheduler/scd_utils.py
  scheduler/schedule_modifier.py
  tests/experiments/experiment_unittests.py
  tests/scheduler/complicated_schedule.swg
  tests/scheduler/test_scheduler.py
Labels: enhancement, improve-code

#468 Fix for radar hanging after USRP Driver initialization on lab computer.
  src/usrp_drivers/usrp_driver.cpp
Labels: bug, quick review
