Repository SuperDARNCanada/borealis, pull requests merged in 2024-01, with the labels that each got.

#428 Remove restriction on max number of range gates.
  src/experiment_prototype/experiment_slice.py
  tests/experiments/experiment_unittests.py
Labels: bug

#429 Scheduler crashing bugfix
  scheduler/remote_server.py
Labels: bug, quick review

#430 Fix ReadTheDocs formatting
  docs/.readthedocs.yaml
  docs/conf.py
  docs/requirements.txt
  docs/source/setup_software.rst
Labels: bug, documentation, quick review
